site_name: "Ceylon AI"
site_url: "https://ceylon.ai"
repo_url: https://github.com/ceylonai/ceylon
repo_name: ceylonai/ceylon
copyright: Copyright 2025 Syigen LTD
extra:
  # hide the "Made with Material for MkDocs" message
  generator: false
  version:
    provider: ceylon

theme:
  name: "material"
  #  custom_dir: docs/.overrides
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: black
      accent: purple
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: purple
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/lightbulb-auto-outline
        name: "Switch to system preference"
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.path
    #    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - toc.follow
  #    - navigation.tabs  # don't use navbar tabs
  logo: "img/logo.png"
  favicon: "favicon.ico"
  locale: en
  highlightjs: true

extra_css:
  - "extra/tweaks.css"


use_directory_urls: false

plugins:
  - search
  - tags

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists # this means you can start a list from any number
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format