[tool.poetry]
name = "ceylon-llm"
version = "0.1.0"
description = ""
authors = ["Dewmal <dewmal@syigen.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
